### ISSUE TITLE
Binary name oran-o2ims or just o2ims 

### ISSUE THREAD

**Issue by tshefi** [openshift-kni/oran-o2ims#104]
Cloned the repo, ran 'make binary'  indeed created the oran-o2ims binary,  
however if we issue the --help  flag, we're suggesting the command should be just "o2ims"
yet there is no such binary, a bit confusing,
either we rename the created binary to o2ims or update help's output.

$ ./oran-o2ims --help
{"time":"2024-06-20T08:50:29Z","level":"INFO","msg":"Command","args":["./oran-o2ims","--help"]}
O2 IMS

Usage:
  o2ims [command]
Available Commands:
  completion  Generate the autocompletion script for the specified shell
..
Use "o2ims [command] --help" for more information about a command.

**Comment by jhernand** [comment]
Certainly confusing, fixed in #105 changing the help text.

**Comment by jhernand** [comment]
Fixed in #105.
