### ISSUE TITLE
oran-o2ims start command's help doesn't reference  start operator command

### ISSUE THREAD

**Issue by tshefi** [openshift-kni/oran-o2ims#106]
While trying to get operator deployment,  [here](https://issues.redhat.com/browse/MGMT-16144) it's suggest,  that  the operator should be started with:  
 oran-o2ims start operator --config=/my/config/file.yaml

Checking oran-o2ims start's  help doesn't document the option to start the operator
I think this wasn't yet implemented yet (maybe) or was but in another way. 

$ ./oran-o2ims start --help
{"time":"2024-06-20T09:43:02Z","level":"INFO","msg":"Command","args":["./oran-o2ims","start","--help"]}
Starts components

Usage:
  o2ims start [command]

Available Commands:
  alarm-server              Starts the alarm server
  alarm-subscription-server Starts the alarm Subscription Server
  controller-manager        Starts the controller manager
  deployment-manager-server Starts the deployment manager server
  metadata-server           Starts the metadata server
  resource-server           Starts the resource server
  operator                       Deploy ......   <---- similar line is missing, might be added in the future.

**Comment by jhernand** [comment]
The "start operator" command was an initial suggestion. The actual way to start the operator is `start controller-manager`.
