### ISSUE TITLE
Update to go 1.22 on DockerFile/Containerfile 

### ISSUE THREAD

**Issue by tshefi** [openshift-kni/oran-o2ims#109]
Not sure  it's correct/critical, I recently ran make install which requested go 1.22
Shouldn't we update to go 1.22 on the linked files below:

https://github.com/openshift-kni/oran-o2ims/blob/main/Dockerfile#L2

https://github.com/openshift-kni/oran-o2ims/blob/main/Containerfile#L24
The comment itself  needs an update as rhel 9 does support go 1.21 
but we still need 1.22 which isn't (yet supported) but still needed.

**Comment by jhernand** [comment]
Requiring Go 1.22 was a mistake introduced in #99. Should be fixed in #110.
