### ISSUE TITLE
No point to set owner to itself

### ISSUE THREAD

**Issue by jc-rh** [openshift-kni/oran-o2ims#276]
https://github.com/openshift-kni/oran-o2ims/blob/b916e324f774dfc4906f1e5f451fb0c60ee2b7a5/internal/controllers/clustertemplate_controller.go#L338

**Comment by Missxiaoguo** [comment]
Yes, I found that ownerObject is not set to nil. I plan to include this fix in my PR for switching to ownerReference for provReq created resources.

**Comment by Missxiaoguo** [comment]
Fixed in https://github.com/openshift-kni/oran-o2ims/pull/279
